name: Build & release implot

on:
  push:
    tags:
      - implot-v[0-9]+.[0-9]+*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.configuration }} ${{ matrix.linkage }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup_tools_shared

      - name: Install further implot dependencies
        shell: bash
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: sudo apt-get install -q -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev

      - name: Build Implot
        shell: bash
        run: ${{ matrix.os == 'ubuntu-22.04' && 'xvfb-run' || '' }} ./generate_implot_libs.sh

      - name: Bundle platform package
        shell: bash
        run: |
          case "${{ matrix.os }}" in
            ubuntu-22.04) ARCHIVE_NAME="implot-linux.tar.xz" ; FOLDER_NAME="linux" ;;
            macos-14)    ARCHIVE_NAME="implot-macos.tar.xz" ; FOLDER_NAME="mac" ;;
            windows-2022) ARCHIVE_NAME="implot-windows.tar.xz" ; FOLDER_NAME="v10" ;;
          esac

          tar -cJvf "$ARCHIVE_NAME" "$FOLDER_NAME"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
      - name: Determine version from tag
        shell: bash
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: staging

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "${{ github.ref_name }}"
          body: 'Build for ${{ github.ref_name }} containing static debug and release files per platform'
          files: staging/**/*.tar.xz
